from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from ..domain.rooming import RoomAssignment, RoomingList, RoomMember
from ..errors import ValidationError
from ..infrastructure.rooming_ooxml import OoxmlCell, OoxmlDocument, OoxmlTable, read_ooxml


@dataclass(frozen=True, slots=True)
class _Columns:
    room: int
    sequence: int
    combined_name: int | None
    chinese_name: int | None
    english_name: int | None
    remarks: tuple[int, ...]


@dataclass(slots=True)
class _RoomDraft:
    source_label: str | None
    members: list[RoomMember]


def parse_rooming_list(path: Path) -> RoomingList:
    path = path.expanduser().resolve()
    if not path.is_file():
        raise ValidationError("Rooming list file does not exist", {"path": str(path)})
    document = read_ooxml(path)
    return parse_rooming_document(document, source_path=path)


def parse_rooming_document(document: OoxmlDocument, *, source_path: Path) -> RoomingList:
    selected = _select_table(document.tables)
    if selected is None:
        raise ValidationError(
            "Could not find a rooming-list table",
            {"path": str(source_path)},
        )
    table, header_index, columns = selected
    drafts: list[_RoomDraft] = []
    current: _RoomDraft | None = None

    for row in table.rows[header_index + 1 :]:
        sequence = _cell_text(row, columns.sequence)
        name_values = _name_values(row, columns)
        if not sequence and not any(name_values):
            continue
        if sequence and not re.search(r"\d", sequence):
            continue

        room_cell = _cell(row, columns.room)
        begins_room = (
            current is None
            or bool(room_cell.text.strip())
            or room_cell.vertical_merge == "restart"
        )
        if begins_room:
            current = _RoomDraft(source_label=room_cell.text.strip() or None, members=[])
            drafts.append(current)

        assert current is not None
        remarks = tuple(
            text for index in columns.remarks if (text := _cell_text(row, index))
        )
        chinese, english, honorific = _parse_names(*name_values)
        current.members.append(
            RoomMember(
                sequence=_normalize_sequence(sequence),
                chinese_name=chinese,
                english_name=english,
                honorific=honorific,
                notes=remarks,
                extra_bed=any("加床" in note for note in remarks),
                no_bed=any("不佔床" in note or "不占床" in note for note in remarks),
            )
        )

    if not drafts:
        raise ValidationError("Rooming-list table has no passenger rows", {"path": str(source_path)})

    warnings: list[str] = []
    rooms: list[RoomAssignment] = []
    for index, draft in enumerate(drafts, 1):
        room_id = _room_id(draft.source_label, index)
        if not _source_has_room_id(draft.source_label):
            warnings.append(f"room {room_id}: source room number missing; generated by row order")
        sleeping = sum(not member.no_bed for member in draft.members)
        room_type = _room_type(draft.source_label, sleeping)
        bed_preference = _bed_preference(draft.members)
        if bed_preference == "conflict":
            warnings.append(f"room {room_id}: conflicting double/twin bed preferences")
            bed_preference = None
        rooms.append(
            RoomAssignment(
                room_id=room_id,
                source_room_label=draft.source_label,
                occupancy=len(draft.members),
                sleeping_occupancy=sleeping,
                room_type=room_type,
                bed_preference=bed_preference,
                members=tuple(draft.members),
            )
        )

    return RoomingList(
        source_path=source_path,
        source_format=source_path.suffix.lower().lstrip("."),
        group_code=_group_code(document.searchable_text),
        rooms=tuple(rooms),
        warnings=tuple(warnings),
    )


def _select_table(
    tables: tuple[OoxmlTable, ...],
) -> tuple[OoxmlTable, int, _Columns] | None:
    best: tuple[int, OoxmlTable, int, _Columns] | None = None
    for table in tables:
        for index, row in enumerate(table.rows):
            columns = _detect_columns(row)
            if columns is None:
                continue
            score = len(table.rows) - index
            if best is None or score > best[0]:
                best = (score, table, index, columns)
    if best is None:
        return None
    return best[1], best[2], best[3]


def _detect_columns(row: tuple[OoxmlCell, ...]) -> _Columns | None:
    normalized = [_header(cell.text) for cell in row]
    room = _find_column(normalized, lambda value: value in {"ROOM", "房號"})
    sequence = _find_column(normalized, lambda value: value in {"NO", "NO.", "序號"})
    english = _find_column(normalized, lambda value: value in {"英文姓名", "英文"})
    chinese = _find_column(normalized, lambda value: value == "中文姓名")
    if chinese is None and english is not None:
        chinese = _find_column(normalized, lambda value: value == "姓名")
    combined = _find_column(
        normalized,
        lambda value: (
            "姓名" in value and value not in {"中文姓名", "英文姓名"}
        )
        or ("ENGLISHNAME" in value and "CHINESENAME" in value),
    )
    if combined is None and chinese is None and english is None:
        combined = _find_column(normalized, lambda value: value == "姓名")
    if room is None or sequence is None or (combined is None and chinese is None):
        return None
    remarks = tuple(
        index
        for index, value in enumerate(normalized)
        if "備註" in value or value == "REMARK" or "房型" in value
    )
    return _Columns(room, sequence, combined, chinese, english, remarks)


def _name_values(
    row: tuple[OoxmlCell, ...], columns: _Columns
) -> tuple[str, str, str]:
    return (
        _cell_text(row, columns.combined_name) if columns.combined_name is not None else "",
        _cell_text(row, columns.chinese_name) if columns.chinese_name is not None else "",
        _cell_text(row, columns.english_name) if columns.english_name is not None else "",
    )


def _parse_names(combined: str, chinese: str, english: str) -> tuple[str | None, str | None, str | None]:
    honorific_match = re.search(r"(MR|MS|CHD)\.?\s+", combined or english, re.I)
    honorific = honorific_match.group(1).upper() if honorific_match else None
    if chinese or english:
        return chinese.strip() or None, _clean_english(english), honorific

    value = combined.strip()
    if not value:
        return None, None, honorific
    title = re.search(r"(?:MR|MS|CHD)\.?\s+", value, re.I)
    if title and re.search(r"[\u3400-\u9fff]", value[: title.start()]):
        chinese_value = value[: title.start()].strip()
        english_value = value[title.end() :].strip()
    else:
        body = value[title.end() :] if title else value
        first_cjk = re.search(r"[\u3400-\u9fff]", body)
        if first_cjk:
            english_value = body[: first_cjk.start()].strip()
            chinese_value = body[first_cjk.start() :].strip()
        else:
            english_value, chinese_value = body, ""
    return chinese_value or None, _clean_english(english_value), honorific


def _clean_english(value: str) -> str | None:
    value = re.sub(r"\s+", " ", value).strip(" .")
    return value or None


def _bed_preference(members: list[RoomMember]) -> str | None:
    text = " ".join(note for member in members for note in member.notes).upper()
    wants_double = "大床" in text or "DBL" in text
    wants_twin = "二小床" in text or "兩小床" in text or "TWN" in text
    if wants_double and wants_twin:
        return "conflict"
    if wants_double:
        return "double"
    if wants_twin:
        return "twin"
    return None


def _room_type(label: str | None, sleeping: int) -> str:
    normalized = (label or "").upper()
    if "TRP" in normalized or "3人" in normalized:
        return "triple"
    if "TWN" in normalized:
        return "twin"
    if "DBL" in normalized:
        return "double"
    return {1: "single", 2: "double_or_twin", 3: "triple"}.get(sleeping, "multiple")


def _room_id(label: str | None, index: int) -> str:
    if not _source_has_room_id(label):
        return f"{index:02d}"
    match = re.search(r"\d+", label or "")
    return match.group(0) if match else f"{index:02d}"


def _source_has_room_id(label: str | None) -> bool:
    return bool(re.fullmatch(r"\s*\d{1,4}\s*(?:TWN|TRP|DBL)?\s*", label or "", re.I))


def _group_code(text: str) -> str | None:
    match = re.search(
        r"(?:TOUR\s*[：:]\s*|團\s*號\s*[：:]?\s*)([A-Z0-9]+)",
        text,
        re.I,
    )
    return match.group(1).upper() if match else None


def _normalize_sequence(value: str) -> str | None:
    value = value.strip()
    if not value:
        return None
    if re.fullmatch(r"\d+(?:\.0+)?", value):
        return str(int(float(value)))
    return value


def _header(value: str) -> str:
    return re.sub(r"[\s\u00a0]", "", value).upper()


def _find_column(values: list[str], predicate) -> int | None:
    return next((index for index, value in enumerate(values) if predicate(value)), None)


def _cell(row: tuple[OoxmlCell, ...], index: int) -> OoxmlCell:
    return row[index] if index < len(row) else OoxmlCell("")


def _cell_text(row: tuple[OoxmlCell, ...], index: int) -> str:
    return _cell(row, index).text.strip()
